// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVJpSE7dWkt6aCYKz4W_WnmGuaF_NMYe0',
    appId: '1:522525425327:web:9f3af277ef46d8a45d1e5a',
    messagingSenderId: '522525425327',
    projectId: 'fooddelivery-7bdcc',
    authDomain: 'fooddelivery-7bdcc.firebaseapp.com',
    storageBucket: 'fooddelivery-7bdcc.appspot.com',
    measurementId: 'G-ZCQHJD83F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexQTfHnveBysuy7Yt9zQ8NjFzjkq-gVM',
    appId: '1:522525425327:android:62df32d3a3aed9e15d1e5a',
    messagingSenderId: '522525425327',
    projectId: 'fooddelivery-7bdcc',
    storageBucket: 'fooddelivery-7bdcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwHRvTdhGSDvCRSppmslL4X0vSPq0V40',
    appId: '1:522525425327:ios:752cb3c2abedca8e5d1e5a',
    messagingSenderId: '522525425327',
    projectId: 'fooddelivery-7bdcc',
    storageBucket: 'fooddelivery-7bdcc.appspot.com',
    iosBundleId: 'com.example.quickFoodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiwHRvTdhGSDvCRSppmslL4X0vSPq0V40',
    appId: '1:522525425327:ios:f76a383c86da0fd25d1e5a',
    messagingSenderId: '522525425327',
    projectId: 'fooddelivery-7bdcc',
    storageBucket: 'fooddelivery-7bdcc.appspot.com',
    iosBundleId: 'com.example.quickFoodDelivery.RunnerTests',
  );
}
